;
; Packer for the Graphics
;
packfile.s = "../graphics.pak"
srcdir.s = "../tiles/"

IncludeFile "Packer.pbi"

DataSection
Data.s "animationen.png"
Data.s "buttons.png" 
Data.s "buttons2.png"
Data.s "buttons3.png"
Data.s "buttons4.png"
Data.s "buttons5.png"
Data.s "buttons_back.png"
Data.s "characters.png"
Data.s "end.jpg"
Data.s "fsi0.jpg"
Data.s "fsi1.jpg"
Data.s "fsi2.jpg"
Data.s "fsi3.jpg"
Data.s "fsi4.jpg"
Data.s "fsi5.jpg"
Data.s "fsi6.jpg"
Data.s "fsi7.jpg"
Data.s "fsi8.jpg"
Data.s "fsi9.jpg"
Data.s "fsi10.jpg"
Data.s "fsi11.jpg"
Data.s "fsi12.jpg"
Data.s "fsi13.jpg"
Data.s "fsi14.jpg"
Data.s "fsi15.jpg"
Data.s "fsi16.jpg"
Data.s "fsi17.jpg"
Data.s "fsi18.jpg"
Data.s "fsi19.jpg"
Data.s "fsi20.jpg"
Data.s "jewels.png"
Data.s "logo.png"
Data.s "monster.png"
Data.s "sight.png"
Data.s "smallchara.png"
Data.s "smallmonster.png"
Data.s "smallmonsteranim.png"
Data.s "smalltiles.png"
Data.s "stars.png"
Data.s "tiles.png"
Data.s "splash1.jpg"
Data.s "splash3.png"
Data.s "items.png"
Data.s "monsteranim.png"
Data.s "enchantments.png"
Data.s "fx.png"
Data.s "projektile.png"
Data.s "body.png"
Data.s "monsterstatus.png"
Data.s "rahmen_oben.png"
Data.s "rahmen_oben2.png"
Data.s "rahmen_links.png"
Data.s "rahmen_unten.png"
Data.s "rahmen_unten2.png"
Data.s "rahmen_rechts.png"
Data.s "rahmen_mitte.png"
Data.s "rahmen_schmal1.png"
Data.s "rahmen_schmal2.png"
Data.s "rahmen_waagrecht.png"
Data.s "icons.png"
Data.s "fsi21.png"
Data.s "mana.png"
Data.s "leben.png"
Data.s "elements.png"
Data.s "fonts.png"
Data.s "swing.png"
Data.s "numbers.png"
Data.s "mousepointers.png"
Data.s "lore.jpg"
Data.s "fsi22.jpg"
Data.s "fsi23.jpg"
Data.s "fsi24.jpg"
Data.s "cleaner.png"
Data.s "used_field.jpg"
Data.s ""
EndDataSection
; IDE Options = PureBasic 4.20 (Linux - x86)
; CursorPosition = 16
; FirstLine = 2
; Folding = -
; EnableXP
; EnableOnError
; DisableDebugger